import { Tutorial } from 'packages/types/src/tutorial.types';

export const mockTutorials: Tutorial[] = [
  {
    id: '1',
    title: 'Introduction to VR Development with Unity',
    url: 'https://example.com/vr-unity-intro',
    category: 'VR',
    difficulty: 'Beginner',
    publishDate: '2024-01-15T10:00:00Z',
    popularity: 1500,
    description: 'Learn the basics of VR development using the Unity engine. Covers setup, basic interactions, and building your first VR scene.',
    tags: ['VR', 'Unity', 'Game Development', 'Beginner'],
    thumbnailUrl: 'https://example.com/thumbnails/vr-unity-intro.png',
    author: 'VR Masterclass',
  },
  {
    id: '2',
    title: 'Advanced AI Filmmaking Techniques',
    url: 'https://example.com/ai-filmmaking-advanced',
    category: 'AI Filmmaking',
    difficulty: 'Advanced',
    publishDate: '2024-03-10T14:30:00Z',
    popularity: 2200,
    description: 'Explore cutting-edge AI tools and workflows for professional film production, including script generation, deepfake prevention, and AI-driven editing.',
    tags: ['AI', 'Filmmaking', 'Machine Learning', 'Advanced', 'Post-production'],
    thumbnailUrl: 'https://example.com/thumbnails/ai-filmmaking-advanced.png',
    author: 'Cinema AI',
  },
  {
    id: '3',
    title: 'Getting Started with Blender for XR',
    url: 'https://example.com/blender-xr-basics',
    category: 'XR',
    difficulty: 'Beginner',
    publishDate: '2024-02-20T09:00:00Z',
    popularity: 1800,
    description: 'A beginner-friendly guide to using Blender for creating 3D assets for XR (AR/VR/MR) applications.',
    tags: ['Blender', '3D Modeling', 'XR', 'Beginner'],
    thumbnailUrl: 'https://example.com/thumbnails/blender-xr-basics.png',
    author: '3D Guru',
  },
  {
    id: '4',
    title: 'Open Source Video Editing with Kdenlive',
    url: 'https://example.com/kdenlive-tutorial',
    category: 'Open Source Creative Tools',
    difficulty: 'Intermediate',
    publishDate: '2023-12-01T11:00:00Z',
    popularity: 950,
    description: 'Master Kdenlive, a powerful open-source video editor. Covers timeline editing, effects, color correction, and exporting.',
    tags: ['Video Editing', 'Open Source', 'Kdenlive', 'Intermediate'],
    thumbnailUrl: 'https://example.com/thumbnails/kdenlive-tutorial.png',
    author: 'Open Source Hub',
  },
  {
    id: '5',
    title: 'Intermediate VR Interactions in Unreal Engine',
    url: 'https://example.com/vr-unreal-intermediate',
    category: 'VR',
    difficulty: 'Intermediate',
    publishDate: '2024-04-05T16:00:00Z',
    popularity: 1250,
    description: 'Take your VR development skills to the next level with complex interactions in Unreal Engine, including physics-based grabbing and UI.',
    tags: ['VR', 'Unreal Engine', 'Game Development', 'Intermediate'],
    thumbnailUrl: 'https://example.com/thumbnails/vr-unreal-intermediate.png',
    author: 'Unreal Wizards',
  },
  {
    id: '6',
    title: 'AI for Scriptwriters: Tools and Best Practices',
    url: 'https://example.com/ai-scriptwriting',
    category: 'AI Filmmaking',
    difficulty: 'Intermediate',
    publishDate: '2024-05-01T09:30:00Z',
    popularity: 3100,
    description: 'Learn how AI tools can assist in scriptwriting, from idea generation and character development to dialogue polishing.',
    tags: ['AI', 'Scriptwriting', 'Filmmaking', 'Intermediate', 'Creative Writing'],
    thumbnailUrl: 'https://example.com/thumbnails/ai-scriptwriting.png',
    author: 'Script AI Academy',
  },
  {
    id: '7',
    title: 'Building Your First AR App with ARKit',
    url: 'https://example.com/arkit-beginner-guide',
    category: 'XR',
    difficulty: 'Beginner',
    publishDate: '2024-03-25T13:15:00Z',
    popularity: 1600,
    description: 'A step-by-step tutorial for iOS developers looking to build their first Augmented Reality application using ARKit.',
    tags: ['AR', 'iOS', 'ARKit', 'Mobile Development', 'Beginner'],
    thumbnailUrl: 'https://example.com/thumbnails/arkit-beginner-guide.png',
    author: 'Apple Dev Tutorials',
  },
  {
    id: '8',
    title: 'Advanced GIMP Techniques for Digital Artists',
    url: 'https://example.com/gimp-advanced',
    category: 'Open Source Creative Tools',
    difficulty: 'Advanced',
    publishDate: '2024-02-10T18:00:00Z',
    popularity: 750,
    description: 'Unlock the full potential of GIMP with advanced techniques for photo manipulation, digital painting, and graphic design.',
    tags: ['GIMP', 'Photo Editing', 'Digital Art', 'Open Source', 'Advanced'],
    thumbnailUrl: 'https://example.com/thumbnails/gimp-advanced.png',
    author: 'GIMP Masters',
  },
  {
    id: '9',
    title: 'WebXR Fundamentals: Creating VR/AR for the Browser',
    url: 'https://example.com/webxr-fundamentals',
    category: 'XR',
    difficulty: 'Intermediate',
    publishDate: '2024-04-15T10:30:00Z',
    popularity: 1950,
    description: 'Learn to build immersive VR and AR experiences that run directly in web browsers using WebXR.',
    tags: ['WebXR', 'JavaScript', 'Web Development', 'VR', 'AR', 'Intermediate'],
    thumbnailUrl: 'https://example.com/thumbnails/webxr-fundamentals.png',
    author: 'Mozilla XR Team',
  },
  {
    id: '10',
    title: 'Understanding Generative AI in Creative Workflows',
    url: 'https://example.com/generative-ai-creative',
    category: 'AI Filmmaking',
    difficulty: 'Beginner',
    publishDate: '2024-05-10T12:00:00Z',
    popularity: 2500,
    description: 'An overview of generative AI technologies (images, text, audio) and how they can be ethically integrated into creative projects.',
    tags: ['Generative AI', 'AI', 'Creative Tools', 'Ethics', 'Beginner'],
    thumbnailUrl: 'https://example.com/thumbnails/generative-ai-creative.png',
    author: 'AI Ethics Initiative',
  }
];
