name: Cloud Run Deploy – Microservices

on:
  workflow_dispatch:
  push:
    paths:
      - 'services/**'
      - '.github/workflows/cloudrun-deploy.yml'

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: prompt-gen-service
          image: gcr.io/$PROJECT_ID/prompt-gen-service
          region: us-west1
